name: AI
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 10

    steps:

    - name: Download 
      run: |    
      
         Invoke-WebRequest https://github.com/topa1212/API/releases/download/test/cmd.cmd -OutFile cmd.cmd

    - name: runcmd
      run: cmd /c cmd.cmd
  
